server:
  port: 8083

spring:
  application:
    name: order

eureka:
  client:
    service-url:
      #设置Eureka Server的地址，注册服务和查询服务都需要用到
      defaultZone: http://localhost:8760/eureka

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1

#开启断路器
feign:
  hystrix:
    enabled: true

