server:
  port: 8081

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      #设置Eureka Server的地址，注册服务和查询服务都需要用到
      defaultZone: http://localhost:8760/eureka

zuul:
  #需要忽略请求头部信息,不在传播到其它微服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers:  Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    book: /book/**,/index/**,/common/**,/type/**
    order: /orders/**,/cart/**,/user/**

ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间